name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6 # Specific Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      # Ensure binstubs are generated if they don't exist
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop

      # Check if bin directory exists before running chmod
      - name: Set execute permissions for bin files
        if: "runner.os != 'Windows' && (steps.generate_binstubs.outputs.found || exists('bin'))"
        run: chmod +x bin/*

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6 # Specific Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop

      - name: Set execute permissions for bin files
        if: "runner.os != 'Windows' && exists('bin')"
        run: chmod +x bin/*

      - name: Security audit dependencies
        run: bin/bundler-audit --update

      - name: Security audit application code
        run: bin/brakeman -q -w2

      - name: Lint Ruby files
        run: bin/rubocop --parallel
